"""Forgotten-password resets.

One flow, two ways to receive the code:

* **Emailed** — if SMTP is configured and the account has a real address, the
  code is mailed the moment the customer asks for it.
* **At the counter** — otherwise the request sits `pending` in the admin UI and
  a member of staff issues a code by hand. A customer standing at the shop is
  already identifying themselves in the strongest way available.

The code is stored only as a SHA-256 hash. It is 8 characters from a 32-symbol
alphabet (~40 bits) generated by `secrets`, so a plain hash is the right tool —
the same reasoning as kiosk keys in `enrollment.py`. Brute force is handled by
rate limits and by the code expiring.

Issuing a new code for an account cancels every earlier one, so a code read out
at the counter cannot be raced by one that was emailed ten minutes before.
"""
import hashlib
import hmac
import logging
import secrets
from datetime import timedelta

import bcrypt
from flask import current_app, url_for

from app.extensions import db
from app.models import PasswordReset, User, utcnow
from app.services import mailer

log = logging.getLogger(__name__)

# No I/O/0/1 — these get read aloud across a counter and typed in by hand.
_ALPHABET = ''.join(c for c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ23456789' if c not in 'IO01')
CODE_LENGTH = 8


def _new_code():
    return ''.join(secrets.choice(_ALPHABET) for _ in range(CODE_LENGTH))


def hash_code(code):
    """Stable hash of a reset code. Empty input hashes to None."""
    if not code:
        return None
    return hashlib.sha256(code.strip().upper().encode('utf-8')).hexdigest()


def _ttl_minutes():
    return int(current_app.config.get('PASSWORD_RESET_TTL_MINUTES', 30))


def find_account(identifier):
    """Look an account up by username or email. None if there is no match."""
    ident = (identifier or '').strip().lower()
    if not ident:
        return None
    user = User.query.filter_by(username=ident).first()
    if user is None:
        user = User.query.filter_by(email=ident).first()
    return user


def _cancel_outstanding(user_id):
    """Void every live request for an account. Called before issuing a new one."""
    outstanding = PasswordReset.query.filter(
        PasswordReset.user_id == user_id,
        PasswordReset.status.in_(('pending', 'issued')),
    ).all()
    for row in outstanding:
        row.status = 'cancelled'
        row.code_hash = None
    return len(outstanding)


def request_reset(identifier, ip=None):
    """Customer asked to reset. Returns (delivery, sent).

    `delivery` is 'emailed' or 'counter'; `sent` says whether mail actually left
    the building. Both are for the *caller's* logging — the page the customer
    sees must say the same thing either way, so that a stranger cannot use this
    form to find out which usernames exist.
    """
    user = find_account(identifier)
    if user is None:
        return 'unknown', False

    # A guest account is a counter artefact with a throwaway @guest.local
    # address; there is no owner to mail and nothing worth resetting.
    if user.is_guest:
        return 'guest', False

    _cancel_outstanding(user.id)

    code = _new_code()
    row = PasswordReset(
        user_id=user.id,
        code_hash=hash_code(code),
        status='issued',
        delivery='counter',
        requested_ip=ip,
        issued_at=utcnow(),
        expires_at=utcnow() + timedelta(minutes=_ttl_minutes()),
    )
    db.session.add(row)

    sent = False
    if mailer.is_configured() and not user.email.endswith('@guest.local'):
        sent = mailer.send(user.email, 'Your PrintFlow password reset code',
                           _email_body(user, code))
        if sent:
            row.delivery = 'emailed'

    if not sent:
        # Nobody has the code: it was generated and immediately forgotten. Staff
        # must issue a fresh one, which is what 'pending' means to the admin UI.
        row.status = 'pending'
        row.code_hash = None

    db.session.commit()
    return ('emailed' if sent else 'counter'), sent


def issue_at_counter(user, staff_user=None):
    """Staff hand a customer a new code. Returns the plaintext code, once.

    It is never stored and never shown again — a second click issues a second
    code and voids the first.
    """
    _cancel_outstanding(user.id)
    code = _new_code()
    row = PasswordReset(
        user_id=user.id,
        code_hash=hash_code(code),
        status='issued',
        delivery='counter',
        issued_by=getattr(staff_user, 'id', None),
        issued_at=utcnow(),
        expires_at=utcnow() + timedelta(minutes=_ttl_minutes()),
    )
    db.session.add(row)
    db.session.commit()
    return code, row


def verify(identifier, code):
    """Match a code against an account. Returns (user, reset_row) or (None, None)."""
    user = find_account(identifier)
    if user is None or not code:
        return None, None

    digest = hash_code(code)
    candidates = PasswordReset.query.filter_by(
        user_id=user.id, status='issued').all()
    for row in candidates:
        if row.code_hash and hmac.compare_digest(row.code_hash, digest):
            if not row.is_usable():
                return None, None
            return user, row
    return None, None


def consume(user, row, new_password, ip=None):
    """Set the new password and spend the code. Returns a list of problems.

    An empty list means it worked. Also clears any login lockout — someone who
    just proved they hold the reset code should not be kept out by the failed
    attempts that sent them here in the first place.
    """
    problems = validate_password(new_password)
    if problems:
        return problems

    user.password_hash = bcrypt.hashpw(new_password.encode('utf-8'),
                                       bcrypt.gensalt()).decode('utf-8')
    user.password_changed_at = utcnow()
    user.failed_login_count = 0
    user.locked_until = None

    row.status = 'used'
    row.used_at = utcnow()
    row.used_ip = ip
    row.code_hash = None

    # Any other code for this account dies with it.
    for other in PasswordReset.query.filter(
            PasswordReset.user_id == user.id,
            PasswordReset.id != row.id,
            PasswordReset.status.in_(('pending', 'issued'))).all():
        other.status = 'cancelled'
        other.code_hash = None

    db.session.commit()
    return []


def validate_password(password):
    """The same rules registration enforces."""
    problems = []
    if len(password or '') < 8:
        problems.append('Password must be at least 8 characters.')
    if not any(c.isdigit() for c in password or '') or \
            not any(c.isalpha() for c in password or ''):
        problems.append('Password must contain letters and digits.')
    return problems


def pending_requests():
    """Requests waiting on staff, newest first."""
    return PasswordReset.query.filter_by(status='pending').order_by(
        PasswordReset.created_at.desc()).all()


def live_codes():
    """Codes already issued and not yet spent — so staff can see what is out."""
    return [r for r in PasswordReset.query.filter_by(status='issued').order_by(
        PasswordReset.issued_at.desc()).all() if not r.is_expired]


def expire_stale():
    """Mark past-dated requests expired. Returns how many."""
    stale = [r for r in PasswordReset.query.filter(
        PasswordReset.status.in_(('pending', 'issued'))).all() if r.is_expired]
    for row in stale:
        row.status = 'cancelled'
        row.code_hash = None
    if stale:
        db.session.commit()
    return len(stale)


def _email_body(user, code):
    try:
        link = url_for('auth.reset_password', _external=True)
    except Exception:
        link = (current_app.config.get('SITE_URL') or '').rstrip('/') + '/reset'
    return (
        f"Hello {user.full_name},\n\n"
        f"Your PrintFlow password reset code is:\n\n"
        f"    {code}\n\n"
        f"Enter it here, along with your username, to choose a new password:\n"
        f"    {link}\n\n"
        f"The code expires in {_ttl_minutes()} minutes and can only be used once.\n\n"
        f"If you did not ask for this, you can ignore this email — your password\n"
        f"has not changed.\n"
    )
